### ISSUE TITLE
Releases Missing in V1 API

### ISSUE THREAD

**Issue by theory** [metacpan/metacpan-api#496]
I tried updating [rpmcpan](/iovation/rpmcpan) to use the v1 API, but I got a bunch of failures:

```
ERROR: Request for release/Cpanel-JSON-XS failed: 404 Not Found
ERROR: Request for release/Devel-PPPort failed: 404 Not Found
ERROR: Request for release/Term-ReadLine-Gnu failed: 404 Not Found
ERROR: Request for release/CGI failed: 404 Not Found
ERROR: Request for module/App::Fatpacker failed: 404 Not Found
ERROR: Request for release/libintl-perl failed: 404 Not Found
ERROR: Request for release/Business-CreditCard failed: 404 Not Found
ERROR: Request for release/Mojolicious failed: 404 Not Found
ERROR: Request for release/Pegex failed: 404 Not Found
ERROR: Request for release/Mail-Sender failed: 404 Not Found
```

Sure enough, these releases are present in the v0 API but not V1. For example:
- [v1 Cpanel-JSON-XS](https://api-v1.metacpan.org/release/Cpanel-JSON-XS)
- [v0 Cpanel-JSON-XS](http://api.metacpan.org/v0/release/Cpanel-JSON-XS)

The v1 link is a 404; the v0 link is not. Maybe the index isn't fully populated or something? Anyway, I'm reverting to v0 for now.

**Comment by ranguard** [comment]
@theory thanks for testing, we'll work out what's wrong and get back to you

**Comment by mickeyn** [comment]
@ranguard it seems some entries in the `release` index don't get `status` set to `latest`.
I fixed it for `Cpanel-JSON-XS` by manually running `latest` script with `--forced`.
We can try using `--forced` in the cron for now until we figure out why this happens

**Comment by kentfredric** [comment]
I did a bit of digging and it seems a significant number of things released since Jun 7th are not indexed.

https://v1.metacpan.org/release/PABLROD/Chart-Dygraphs-0.001 # For instance is clearly there, but if you click the "latest" link on that page, you get a 404. 

And this problem is more pronounced the more recent a release is. 

For instance:

https://v1.metacpan.org/release/JHI/Time-HiRes-1.9737  # released 11 hours ago, still not recognised as "latest", latest link 404s.

In fact, I am yet to find *any* distributions listed on todays: https://v1.metacpan.org/recent that don't suffer this problem.

For instance, Moo was released today .... sure enough:

404: https://v1.metacpan.org/release/Moo

**Comment by mickeyn** [comment]
it's not that the releases are not indexed, we just had an issue with the marking as 'latest'.
though we are still investigating the source of it, we put in place a mitigation cron to deal with it.
all the examples you gave now work.

@theory, @kentfredric: can you please recheck and let us know if you notice any other issues related to this?

**Comment by kentfredric** [comment]
I see this issue no longer, will report back if it comes back :)

**Comment by theory** [comment]
Still getting quite a few 404s:

    ERROR: Request for module/B::C failed: 404 Not Found
    ERROR: Request for module/App::Fatpacker failed: 404 Not Found
    ERROR: Request for module/Types::Serialiser failed: 404 Not Found
    ERROR: Request for release/Test-Harness failed: 404 Not Found
    ERROR: Request for release/SOAP-Transport-JABBER failed: 404 Not Found
    ERROR: Request for module/Convert::BinHex failed: 404 Not Found
    ERROR: Request for module/XML::Stream failed: 404 Not Found
    ERROR: Request for module/DBM::Deep failed: 404 Not Found
    ERROR: Request for module/mod_perl failed: 404 Not Found
    ERROR: Request for release/mod_perl failed: 404 Not Found
    ERROR: Request for release/SOAP-Lite failed: 404 Not Found

**Comment by mickeyn** [comment]
all these work now (just correct `module/App::Fatpacker` to `module/App::FatPacker`, it's case sensitive).
can we close this issue?

**Comment by kentfredric** [comment]
Bunch of dual life things flared up. Something is broken in indexer.

https://v1.metacpan.org/release/Module::Metadata # 404
https://v1.metacpan.org/release/Locale::MakeText
https://v1.metacpan.org/release/Module::CoreList

**Comment by mickeyn** [comment]
fixed. note that `Locale-Maketext` has wrong casing in the URL you posted.

**Comment by mickeyn** [comment]
can we close this one?

**Comment by kentfredric** [comment]
I'd say "yes" instinctually, but I don't know why it was happening in the first place, and it flares up episodically, so there's no way from *my* perspective to decide if its fixed or not.

I can only say I no longer see the problem, ( but it could still be there )

**Comment by theory** [comment]
It happened as recently as yesterday (#513).

**Comment by oalders** [comment]
@theory is this still an ongoing issue?

**Comment by tsibley** [comment]
All examples mentioned here look fixed, including the most recent from 24 Aug in #513 as noted by @theory above.

I'm not sure what @mickeyn was doing to fix them, so it's hard to know if the root cause is fixed.

**Comment by theory** [comment]
I  haven't seen this issue in a while, no.

**Comment by tsibley** [comment]
Closing then.  We're working on the v1 migration, and the "latest" status of releases is a thing we're watching for discrepancies from v0.

If a similar issue arises, please feel free to open a new ticket!
